apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring_webflux
  tags:
    - spring-webflux
  annotations:
    github.com/project-slug: arulvannala/spring_webflux
    'backstage.io/kubernetes-label-selector': 'app=backstage'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: other
  lifecycle: unknown
  owner: default-team
  system: backstage
