apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: math-demo-live
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: math-demo-live
    app: backstage
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  source:
    git:
      url: https://github.com/arulvannala/spring_webflux
      ref:
        branch: main
